version: '3.8'

services:
  front:
    build: ./front
    env_file:
      - ./.env
    volumes:
      - react_build:/app/public

  back:
    depends_on:
      - front
    build: ./back
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - react_build:/app/build

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - back
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  react_build:






